### PR TITLE
Resolves #1152 "Fix various quirks in OpenSearch archetype projet generation"

### LINKED ISSUE #1152: upgrade io.confluent:kafka-avro-serializer:jar:1.0
This is a very out of date version of this jar and is being reported as having an unknown license in the third party jar list.

This project not appear to publish to maven central - only to 3rd party maven repos.

https://mvnrepository.com/artifact/io.confluent/kafka-avro-serializer?repo=confluent-packages

### PR DESCRIPTION
**Pull request by rzo1**
Developer Certificate of Origin
===============================

By contributing to StormCrawler, you accept and agree to the following terms and conditions (the *Developer Certificate of Origin*) for your present and future contributions submitted to StormCrawler. 
Please refer to the *Developer Certificate of Origin* section in [`CONTRIBUTING.md`](CONTRIBUTING.md) for details.

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

### CODE REVIEW

**Comment by rzo1** [comment]
Cool. The configured maven repository has an invalid / expired certifacte:

```bash
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
Caused by: java.security.cert.CertificateExpiredException: NotAfter: Wed Mar 20 23:59:59 UTC 2024
```

**Comment by jnioche** [comment]
Could we just create links instead of copying the files?

**Comment by rzo1** [comment]
> Could we just create links instead of copying the files?

I switched to symbolic links, which will work in Linux/OSX. For Windows some special git config is required: https://stackoverflow.com/questions/5917249/git-symbolic-links-in-windows

**Comment by rzo1** [comment]
So looks like the `maven.java.net` repository in the action is gone because of an expired certificate. I don't have it locally in my effective pom, so might be an environment thing in GH.

No idea why it is trying to fetch data from

```bash
Caused by: org.eclipse.aether.resolution.ArtifactResolutionException: Could not transfer artifact io.confluent:kafka-avro-serializer:pom:1.0 from/to jvnet-nexus-releases (https://maven.java.net/content/repositories/releases/): transfer failed for https://maven.java.net/content/repositories/releases/io/confluent/kafka-avro-serializer/1.0/kafka-avro-serializer-1.0.pom
```

**Comment by rzo1** [comment]
Will also affect builds on `main` (so not specific to this PR)

**Comment by jnioche** [comment]
Kafka - avro thingy might be one of the sub deps of hadoop which the next release of Storm will get rid of

**Comment by rzo1** [comment]
Discussed via chat. We will do a new PR Here.

**Pull request closed without merging**
