### PR TITLE
[External][Solr] The Solr storage should use 'autoSoftCommit' and 'autoCommit'

### PR DESCRIPTION
**Pull request by ludovic-boutros**
This is a fix proposal for the issue #177.

- No explicits commit in the code
- Add autoCommit and autoSoftCommit in solrconfig files
- Update Lucene version in solrconfig files

### CODE REVIEW

**Comment by jnioche** [comment]
looks good. @jorgelbg any comments?

**Comment by jorgelbg** [comment]
Looks good to me, I'm going to take it for a spin later today.

**Comment by jorgelbg** [comment]
@ludovic-boutros @jnioche :+1: looks good tom me I've done a couple of basic crawl tests and haven't found any problems.

**Comment by jnioche** [comment]
Thanks. Just to be sure I understand correctly @ludovic-boutros, are the documents buffered somehow or do we do 1 request to SOLR per document to index? The latter would seem rather costly

**Comment by ludovic-boutros** [comment]
@jnioche HttpSolrClient and CloudSolrClient do not buffer any updates. 
We could implement a buffering/batch system with callbacks in order to acknowledge updates correctly.
It could be done in a second phase if needed but:
- I don't think it is needed currently
- It could be a bit tricky with SolrCloud if we want to keep routing awareness on the client side

This implementation uses Solr like a NoSql DB and lets the update/commit management be done on the server side.

**Comment by jnioche** [comment]
> HttpSolrClient and CloudSolrClient do not buffer any updates. 
thanks for the clarification @jorgelbg

**Comment by jorgelbg** [comment]
@ludovic-boutros why buffering/queueing of documents with SolrCloud could be tricky? At this point we are not supporting any kind of routing in the client side, except that the CloudSolrClient is topology-aware thanks to Zookeeper and as such it is able of routing the document to the right shard/collection leader. 

For routing purposes we can use the `KEY!ID` syntax to influence routing of documents into specific shards, but still the routing of the document is done on Solr itself. Also an specific field could be used (depending on how the collection is created) to route the documents.

**Comment by ludovic-boutros** [comment]
@jnioche @jorgelbg We forgot to remove the batch size parameters in the wiki.
@jorgelbg I will try to give you an answer soon, quite busy this week ;)

**Comment by ludovic-boutros** [comment]
@jorgelbg ok you are right, I just checked the distribution of a collection of documents in the code. It seems to split correctly the documents across the correct shards.

Which solution would you implement ? 
- create a SolrClient which acknowledge tuples
- other

What should/could be done if only one doc throws an error ?
I remember that Solr is not really wordy on this in its messages.
Perhaps, this should be discussed in another issue.

**Comment by jnioche** [comment]
Hi. Could you please open a new issue for it + create one for fixing the README file 
Thanks!

**Pull request merged**
