### PR TITLE
Adding a README file to the solr module

### PR DESCRIPTION
**Pull request by jorgelbg**
A basic README file containing the provided resources, how to use them, and the different configuration parameters available. Issue https://github.com/DigitalPebble/storm-crawler/issues/155

@jnioche Can you take a look?

### CODE REVIEW

**Comment by jnioche** [comment]
Looks great! Don't we need to predefine the schema for the various indices in SOLR? or can it guess like ES does?

**Comment by jorgelbg** [comment]
This depends on the configuration I think we can provide an example schema.xml file, the one mandatory field should be the url field, the rest is configurable through the topology config file. For testing I used an example configuration that except the mandatory field (url for the IndexerBolt and the StatusUpdaterBolt) it can store/index everything else that you throw at it, using dynamic fields. The downside is that everything is stored as a string, not so useful but handy for testing purposes.

This could work at least as an example, basically I use something like https://github.com/arafalov/simplest-solr-config with the minimum configuration possible, very generic.

I see some options here: 
* Add this default configuration to the module so that can be used directly and explain the basic requirements in the doc.
* Use a more specific schema.xml file (at least with the default fields for each collection in the indexer, metrics, status) that could be attached or included in the README, that it includes the fields extracted by default by the `JsoupParserBolt`. 
* Use the schemaless mode and reference in the README to something like https://cwiki.apache.org/confluence/display/solr/Schemaless+Mode.

Any preference on one particular option?

**Comment by jnioche** [comment]
> Add this default configuration to the module so that can be used directly and explain the basic requirements in the doc.

+1 & mention the schemaless mode in the README as well.

Thanks

**Comment by jorgelbg** [comment]
Ok, I'm going to commit the 3 collections config into this same PR.

**Comment by jnioche** [comment]
Hi @jorgelbg. Could you update the README to mention the schemaless mode and explain the SOLR configs you just added?

**Comment by jorgelbg** [comment]
@jnioche I've added a section "Solr configuration" in the last commit https://github.com/jorgelbg/storm-crawler/commit/8f6f8c26207a73e8bec721c195c9bccb3351bd1e#diff-172fd82a13532797e7558b92543c817aR73 should I add a more comprehensive explanation?

**Comment by jnioche** [comment]
Sorry, had missed that bit when looking at the commits this morning. Thanks!

**Pull request merged**
