### PR TITLE
ES Status configuration : Can override discovered links

### PR DESCRIPTION
**Pull request by Mikwiss**
Add a parameter to override a link in status index with ES StatusUpdaterBolt. 

Context : our topologies _create_ in a filter's ParserBolt some links. Those links aren't in the DOM page, so the classic discover cannot be used. Also, they must not be refetch automatically, only when the filter create it, so the StatusUpdaterBolt have to override the previous fetched one.

Signed-off-by: Mathieu Bret <mikwiss00@gmail.com>

Thanks for contributing to StormCrawler, your efforts are appreciated!

Developer Certificate of Origin
===============================

By contributing to StormCrawler, you accept and agree to the following terms and conditions (the *Developer Certificate of Origin*) for your present and future contributions submitted to StormCrawler. 
Please refer to the *Developer Certificate of Origin* section in [`CONTRIBUTING.md`](CONTRIBUTING.md) for details.

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

Before opening a PR, please check that: 

* You've applied the formatting used by the project with `mvn java-formatter:format`
* You've squashed your commits into a single one
* You've described what the PR does or at least point to a related issue
* You've signed-ff your commits with 'git commit -s'

Thanks!

### CODE REVIEW

**Comment by jnioche** [comment]
hi @Mikwiss and thanks for the PR. Just to make sure I correctly understand what you are trying to achieve: you are creating custom outlinks in a ParseFilter and as these get a default status of DISCOVERED  they won't overwrite any existing value in ES. Is that right?
The trouble is that neither the Scheduling classes nor the Metadata Transfer ones allow you to modify the status for a URL.
So, yes you might need to do it the way you are suggesting, however, instead of one config that would apply to all the discovered URLs. I would rather have that triggered on a per-URL basis based on some arbitrary key in the metadata, just like we do for instance for specifying a custom _nextFetchDate_. 
I can see 2 options:
1. we do it in ES StatusUpdaterBolt only e.g. we use a key like 'es.status.override'
2. we do it in AbstractStatusUpdaterBolt by changing the status value to FETCHED based on an arbitrary key in the MD. You will need to control the _nextFetchDate_ explicitly, rely on the default setting for it or use a custom scheduler.

I am not sure which one of these 2 approaches I like best: the 2nd one is more generic but then it feels a bit wrong to fiddle with the status; the first one is more straightforward - you'd need to modify AbstractStatusUpdater so we bypass the caching.

What do you think?
Can you share a concrete example of the sort of URLs that you would need this mechanism for? There are often more than one way of doing things with StormCrawler.

Thanks

**Comment by Mikwiss** [comment]
Hi @jnioche ! Thanks for reply !

> Just to make sure I correctly understand what you are trying to achieve: you are creating custom outlinks in a ParseFilter and as these get a default status of DISCOVERED they won't overwrite any existing value in ES. Is that right? 

Exactly ! 

> Can you share a concrete example of the sort of URLs that you would need this mechanism for ?

In order to check our e-commerce frontend, we have to fetch and parse product pages (> 100k). For each product, the ParseFilter have to find a specific _<div>_. If the _<div>_ is found, we have to fetch another URL (the marketplace page). The marketplace URL may or not be emitted as an outlink (btw this link is not in the page as it, we build it), depends on the product and the moment. The default fetch interval for a marketplace URL is set to -1.

> you'd need to modify AbstractStatusUpdater so we bypass the caching.

We disable the cache because we control all the input (product page). In another word, we don't discover any links in the page.

> The trouble is that neither the Scheduling classes nor the Metadata Transfer ones allow you to modify the status for a URL. So, yes you might need to do it the way you are suggesting, however, instead of one config that would apply to all the discovered URLs. I would rather have that triggered on a per-URL basis based on some arbitrary key in the metadata, just like we do for instance for specifying a custom _nextFetchDate_. I can see 2 options:
> 
> 1. we do it in ES StatusUpdaterBolt only e.g. we use a key like 'es.status.override'
> 2. we do it in AbstractStatusUpdaterBolt by changing the status value to FETCHED based on an arbitrary key in the MD. You will need to control the _nextFetchDate_ explicitly, rely on the default setting for it or use a custom scheduler.
> 
> I am not sure which one of these 2 approaches I like best: the 2nd one is more generic but then it feels a bit wrong to fiddle with the status; the first one is more straightforward - you'd need to modify AbstractStatusUpdater so we bypass the caching.
> 
> What do you think? 

The second one is more generic but, as you said, fiddle with the status seems strange and not StromCrawler compliant, juste to workaround ESIndexerbolt behaviour.

**Comment by jnioche** [comment]
thanks for the explanation. Any chance you could amend the PR so that the override is done on  a per URL basis with a key like 'es.status.override' ?

**Comment by Mikwiss** [comment]
Sure, let me try it and i'll feedback you 👍

**Comment by jnioche** [comment]
> Sure, let me try it and i'll feedback you +1

any luck with it @Mikwiss ?

**Comment by Mikwiss** [comment]
Hi @jnioche ! I didn't notice your reply, I'm really sorry. This feature is on my backlog and I do a new pull request as soon as I can treat it !

**Pull request closed without merging**
