### PR TITLE
Removed write limit from Tika handler to get full text

### PR DESCRIPTION
**Pull request by dremeika**
Tika shouldn't limit content size. It's already done using http.content.limit property.

### CODE REVIEW

**Comment by jnioche** [comment]
Thanks Donatas, I hadn't noticed the implicit limitation.
I would make sense to add something in the config to be able to limit the size of the text sent, regardless of `http.content.limit`. The latter can influence whether the document will be parseable at all (think pdf docs), sometime you need to set it to -1 but still want to limit the amount of text passed to the following bolts.  The limitation on the text length could also be done in [AbstractIndexerBolt](https://github.com/DigitalPebble/storm-crawler/blob/master/core/src/main/java/com/digitalpebble/storm/crawler/indexing/AbstractIndexerBolt.java).

**Comment by jnioche** [comment]
BTW if you are dealing with HTML docs only I'd recommend that you use the parser in  [https://github.com/PopSugar/storm-crawler-extensions]. Tika filters/normalises the HTML content a lot and if you use XPath expression to extract data from pages then the JSoup based parser should be a better option.

**Comment by dremeika** [comment]
Yes, I am dealing with HTML only and I only need parser to discover outlinks. Tika seems to do the job, but JSoup should perfrom better, I guess. Will try it. Thanks.

**Comment by jnioche** [comment]
@dremeika see [master 6a2d145]. It is now in the core code, thanks to @GuiForget and Shopstyle.com who kindly donated it to Storm Crawler.

**Comment by dremeika** [comment]
Great! Big thanks @GuiForget and @jnioche .

**Pull request merged**
