### PR TITLE
Changed ProtocolFactory to be a singleton but can hold more than one …

### PR DESCRIPTION
**Pull request by jnioche**
…instance of each protocol implementation

See discussion on #918

### CODE REVIEW

**Comment by jnioche** [comment]
Oooof, sorry @sebastian-nagel, that diff is horrible. I must have changed the formatting in Eclipse. On this subject, see https://github.com/DigitalPebble/storm-crawler/discussions/931

**Comment by jnioche** [comment]
Went ahead and added the auto formatting on commits. The diffs are perfect now

**Comment by sebastian-nagel** [comment]
Hi @jnioche, looks good! +1

**Comment by sebastian-nagel** [comment]
One point: add `protocol.instance.num` to crawler-default.yaml?

**Comment by jnioche** [comment]
thanks @sebastian-nagel

**Pull request merged**
