### PR TITLE
Prefix protocol metadata 

### LINKED ISSUE #776: Prefix protocol metadata to avoid that internal metadata fields are accidentally overwritten
HTTP protocol implementations add all HTTP response header fields to the response metadata. The FetcherBolt merges the response metadata into the metadata which is passed forward in the topology as part of the tuples <url, content, metadata>. Existing key-value(s) pairs (persisted in the status index) are overwritten and later eventually stored in the status index (if listed in "metadata.persist") or even transferred to outlinks ("metadata.transfer").

This allows to easily use the response header values for requests, e.g. cookies or "ETag".

However, webadmins are free to send any header back. This may cause unwanted collisions with metadata keys used by crawler-internal classes. E.g. if the server responds with non-standard headers "HostName" or "Depth". Or even standard headers such as "Last-modified" which require to follow a specific format for internal use.

To avoid collisions: Why not prefix protocol metadata: `protocol.content-type` or `http.content-type`? This would also make it clear which component sets the metadata - similar to the prefixes `fetch.` and `parse.` already used. The draw-back would be that users are required to update the configuration.

### PR DESCRIPTION
**Pull request by jnioche**
fixes #776
@sebastian-nagel is that what you had in mind?

### CODE REVIEW

**Comment by sebastian-nagel** [comment]
Looks good. What about the ETag header? Should also get prefixed by default. See 582ead1 ?

**Comment by sebastian-nagel** [comment]
One remark (haven't verified whether this is a problem or not): what happens if there is already some metadata stored in the status index from a prior fetch (eg. "protocol.etag" or just "etag") and now a fetch is made without the "ETag" header in the response? Is the prior value left unchanged? Should it be cleared/removed? - The prefix would allow to safely clear old protocol metadata.

**Comment by sebastian-nagel** [comment]
Handling of cookies also requires changes regarding the prefixed metadata. Here cleaning up the metadata would break handling of cookies: the set-cookie value must be preserved unless a new one is sent by the server. I'll update branch 776 regarding ETag and cookies.

**Comment by sebastian-nagel** [comment]
Also, the WARC writer requires changes as it reads the HTTP headers stored in response metadata.

**Comment by sebastian-nagel** [comment]
Also the parsers required changes to read HTTP Content-Type and status whether content is trimmed.

**Comment by jnioche** [comment]
thanks @sebastian-nagel , will have a look tomorrow

**Comment by jnioche** [comment]
instead of changing all the key names (which makes the code a bit more difficult to read) - what about adding _getFirstValue(key, prefix)_ to metadata?

**Comment by jnioche** [comment]
as a general observation, this is quite a few changes for an issue which is largely hypothetical, but let's see if we can get the right balance

**Comment by sebastian-nagel** [comment]
> getFirstValue(key, prefix) 

To retrieve the cookies also getValues(key, prefix) is required.

I totally agree about the amount of changes. I also didn't expect that many. However, it isn't hypothetical regarding the last-modified date format which is still an open issue (#777) - all because the field is (also) filled from an external server and there are some limitations on the date format (see #492).

**Comment by jnioche** [comment]
@sebastian-nagel have added the 2 methods to Metadata. 
Need to get my head around  **_putAll(Metadata m, String prefix, boolean cleanup)_**

**Comment by sebastian-nagel** [comment]
> use getValue methods with prefix

+1 looks good

**Comment by jnioche** [comment]
@sebastian-nagel do we really need  _public void putAll(Metadata m, String prefix, boolean cleanup)?

we're only using it iin 2 places and with _false_.

I'll add a default value for protocol.md.prefix in the default config of 'protocol.'; anyone upgrading on an existing crawl will have to override it to an empty string - I'll make this clear in the release notes. Leaving it to an empty string by default means no one will set it even for new crawls. What do you think?

**Comment by sebastian-nagel** [comment]
Not necessarily. The the discussion above why I've added the cleanup option and why it cannot be used. The other motivation was to avoid unnecessary String concatenations if the prefix is empty.

I'm in course to run a test crawl with the changes applied, I'll let you know about the results later today.

**Comment by jnioche** [comment]
cleanup -> found your previous comment. Let's remove that method then.

test-> thanks, I'll wait to hear from you before I merge

**Comment by sebastian-nagel** [comment]
Hi @jnioche, the test crawl went well. Passing of protocol metadata to parsers, WARC writers seems to work. Unfortunately, I forgot to set http.use.cookies = true in the config - but cookies are saved in ES status index in metadata ("protocol%2Eset-cookie").

**Comment by jnioche** [comment]
Merged. Thanks @sebastian-nagel

**Pull request merged**
