### PR TITLE
Improve FetcherBolt

### PR DESCRIPTION
**Pull request by XciD**
- Improve the rotation of Queues
- Check if an url is already on a queue

### CODE REVIEW

**Comment by jnioche** [comment]
Thanks @XciD. Could we split this into 2 separate PRs (and squash the commits if necessary)

Usually we control the unicity of the URLs at the spout level, but I suppose that with e.g. queue implementations you don't have any control on that. Is that your case?

I wonder what the overhead of checking for duplicates is, any idea?

**Comment by XciD** [comment]
In my case I've multiple spout so I can control on a spout but not all (maybe with a redis). 
No idea about the overhead, My queues size are low so I think there is no impact...

**Comment by jnioche** [comment]
Do you have multiple instances of the same type of spout or multiple spouts of different types?

**Comment by XciD** [comment]
Differents types, in fact I've a SeedSpout and an OutlinkSpout

**Pull request closed without merging**
