### PR TITLE
Scheduler implementations return an Optional<Date>

### PR DESCRIPTION
**Pull request by jnioche**
implements #861

Using Optional<Date> would have worked but require a big change in the API whereas _null_ allows to keep it as it is.

@sebastian-nagel any thoughts?

### CODE REVIEW

**Comment by jnioche** [comment]
Using _null_ is dirty. Went for Optional<Date> instead.

**Review by sebastian-nagel — CHANGES_REQUESTED** [review]
Looks good.

**Comment by sebastian-nagel** [comment]
One question: so far there's no way to specify a rule for DefaultScheduler so that match items are never refetched. E.g.
```yaml
# never re-fetch spammy pages
fetchInterval.FETCHED.isSpam=true: -1
```

**Comment by jnioche** [comment]
> One question: so far there's no way to specify a rule for DefaultScheduler so that match items are never refetched, right? E.g.
> 
> ```yaml
> # never re-fetch spammy pages
> fetchInterval.FETCHED.isSpam=true: -1
> ```

Good catch! I have fixed that as part of the latest commit.

**Comment by jnioche** [comment]
thanks for the review @sebastian-nagel - please have a look at the latest commit

**Review by sebastian-nagel — APPROVED** [review]

**Pull request merged**
