### PR TITLE
Added metadata.lastProcessedDate to the status stream.

### PR DESCRIPTION
**Pull request by owenrh**

### CODE REVIEW

**Comment by jnioche** [comment]
thanks @owenrh 
I'd rather not change the method signatures just for this and it should not be a mandatory feature. Didn't we mention a different name as well? It is not really when it was fetched but when the process was finished which is not quite the same.
What I had in mind was simply to add it to the metadata in the AbstractStatusUpdater class - users can decide whether to persist it in the storage by adding the key name to the config. It would end up being in the metadata instead of being a brand new field.
What do you think?

**Comment by owenrh** [comment]
@jnioche sure, I think I misunderstood the convo we have on the [issue](https://github.com/DigitalPebble/storm-crawler/issues/327). The _metadata_ approach is definitely less intrusive. Also I thought you weren't too keen on the _lastProcessedDate_ field name, but I obviously got the wrong end of the stick. 

So you'd be cool with the metadata solution with a field name of _lastProcessedDate_? (If so , I'll just trash this PR and create a separate one to avoid having to reverse commits).

**Comment by jnioche** [comment]
+1 Thanks

**Comment by jnioche** [comment]
thanks @owenrh

**Pull request merged**
