### PR TITLE
Can disable MaxDepthFilter

### PR DESCRIPTION
**Pull request by Mikwiss**
Hi all !

We spotted another border side. Our team recently upgrade StormCrawler version (2.2 to 2.5). The MaxDepthFilter was configured to `maxDepth : 0`, and no links was emitted (correct behavior).
After the upgrade, the first link (so with no `depth` in metadata) has emitted a hundred unwanted links. So in order to disable it, I propose to remove a condition in order to handle the `maxDepth : -1` parameter (equals to a disable). 

Let me know if it's ok for you.

Regards.

Signed-off-by: Mathieu Bret <mikwiss00@gmail.com>

Thanks for contributing to StormCrawler, your efforts are appreciated!

Developer Certificate of Origin
===============================

By contributing to StormCrawler, you accept and agree to the following terms and conditions (the *Developer Certificate of Origin*) for your present and future contributions submitted to StormCrawler. 
Please refer to the *Developer Certificate of Origin* section in [`CONTRIBUTING.md`](CONTRIBUTING.md) for details.

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

Before opening a PR, please check that: 

* You've squashed your commits into a single one
* You've described what the PR does or at least point to a related issue
* You've signed-ff your commits with 'git commit -s'
* The code is properly formatted with 'mvn git-code-format:format-code -Dgcf.globPattern=**/*'

Thanks!

### CODE REVIEW

**Comment by jnioche** [comment]
Thanks for reporting this

> Our team recently upgrade StormCrawler version (2.2 to 2.5). The MaxDepthFilter was configured to maxDepth : 0, and no links was emitted (correct behavior).

This was changed in 2.4, see discussion at #959

> After the upgrade, the first link (so with no depth in metadata) has emitted a hundred unwanted links. So in order to disable it, I propose to remove a condition in order to handle the maxDepth : -1 parameter (equals to a disable).

-1 means "disable the filtering i.e let any outlink through", if you want to deactivate any outlink, set the value to 0. This should not change I think.

What should change though is how no existing depth is handled. Currently it is getting -1, like maxDepth but it should be 0 instead. I will commit a fix for it shortly, which will also make the code easier to read.

Feel free to reopen if you think that commit doesn't solve things. Thanks!

PS: haven't forgotten your other PR

**Comment by jnioche** [comment]
Thanks for reporting this. 

The handling of 0 was changed in 2.4, see #959. I need to revisit that decision as it probably wasn't the best way of doing. It is simply that the filtering in that case was applied to the source URL whereas in the rest of the time it is applied to outlinks.

Either way, -1 means something different altogether. It indicates that the filtering should not be applied at all and as such all the outlinks should be produced. 

I will push a commit to simplify that part of the code, we can then think about how to handle #959.

**Comment by jnioche** [comment]
Fixed in c7243e51
Setting the value to 0 should disallow outlinks. Let me know what you think @Mikwiss

**Comment by Mikwiss** [comment]
Hey @jnioche, 

Our team has just tested the fix : https://github.com/DigitalPebble/storm-crawler/commit/c7243e510d65c96844cadbed5fb7477bed5d7df7 

It's perfect ! Much better as my fix, well done !

**Pull request closed without merging**
