### PR TITLE
Updated elasticsearch to 2.2.0

### PR DESCRIPTION
**Pull request by w0mbat**

### CODE REVIEW

**Comment by jnioche** [comment]
Thanks Daniel. Don't the mapping need changing as well? I think TTL has been removed with 2.2.0
Moving to 2.x would probably require a change to the latest version of Kibana. Have you tried the existing dashboard definitions with it?

**Comment by w0mbat** [comment]
@jnioche Sorry, just removed the _id field mapping in my local application - added it now to the codebase. _ttl is deprecated since 2.0, but it generates no error or similar. I am also not aware of an alternative

**Comment by w0mbat** [comment]
@jnioche I updated to your latests commits and resolved a merge conflict that occurred recently

**Comment by jnioche** [comment]
thanks @w0mbat. This is quite a big change for the ES module and I'd rather do that straight after releasing 0.9 so that it gets used as much as possible before releasing it. Does that make sense?

BTW Would a REST-based client (see #221) like Jest work on ES 1.x as well as 2.x?

**Comment by w0mbat** [comment]
@jnioche I can understand the decision to delay it to 0.10
I haven´t used Jest so far, but depending on the jest version, they are claiming to be compatible with ES 1.x and 2.x: https://github.com/searchbox-io/Jest

**Comment by jnioche** [comment]
Note to self -[ breaking changes in 2.x](https://www.elastic.co/guide/en/elasticsearch/reference/current/breaking-changes-2.0.html)

@w0mbat getting [Exception "path.home is not configured"](https://github.com/elastic/elasticsearch/issues/13155) when using embedded mode i.e not specifying any hosts. I presume you are getting this as well?

**Comment by w0mbat** [comment]
@jnioche well, I haven´t seen this one so far. Does it only come with debug logging?

**Comment by jnioche** [comment]
No, it is big bad exception which crashes the topo and it comes both on the UI and the logs with level ERROR

```log
2016-03-16 16:26:16.033 b.s.d.executor [ERROR] 
java.lang.RuntimeException: java.lang.IllegalStateException: path.home is not configured
	at com.digitalpebble.storm.crawler.elasticsearch.persistence.StatusUpdaterBolt.prepare(StatusUpdaterBolt.java:190) ~[stormjar.jar:?]
	at backtype.storm.daemon.executor$fn__5694$fn__5707.invoke(executor.clj:757) ~[storm-core-0.10.0.jar:0.10.0]
	at backtype.storm.util$async_loop$fn__545.invoke(util.clj:477) [storm-core-0.10.0.jar:0.10.0]
	at clojure.lang.AFn.run(AFn.java:22) [clojure-1.6.0.jar:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.7.0_80]
Caused by: java.lang.IllegalStateException: path.home is not configured
	at org.elasticsearch.env.Environment.<init>(Environment.java:101) ~[stormjar.jar:?]
	at org.elasticsearch.node.internal.InternalSettingsPreparer.prepareEnvironment(InternalSettingsPreparer.java:81) ~[stormjar.jar:?]
	at org.elasticsearch.node.Node.<init>(Node.java:128) ~[stormjar.jar:?]
	at org.elasticsearch.node.NodeBuilder.build(NodeBuilder.java:145) ~[stormjar.jar:?]
	at org.elasticsearch.node.NodeBuilder.node(NodeBuilder.java:152) ~[stormjar.jar:?]
	at com.digitalpebble.storm.crawler.elasticsearch.ElasticSearchConnection.getClient(ElasticSearchConnection.java:71) ~[stormjar.jar:?]
	at com.digitalpebble.storm.crawler.elasticsearch.ElasticSearchConnection.getConnection(ElasticSearchConnection.java:130) ~[stormjar.jar:?]
	at com.digitalpebble.storm.crawler.elasticsearch.persistence.StatusUpdaterBolt.prepare(StatusUpdaterBolt.java:186) ~[stormjar.jar:?]
	... 4 more
```

**Pull request closed without merging**
