### PR TITLE
#1049 Replace "Collapse and Expand Results" Solr query with "Result Grouping" query.

### PR DESCRIPTION
**Pull request by syefimov**
Ticket #1049
Replace "Collapse and Expand Results" Solr query with "Result Grouping" query.

### CODE REVIEW

**Comment by jnioche** [comment]
thanks for the PR @syefimov 

I would have been better to have one PR per issue. For instance, the addition of the _DeletionBolt_ could be done while discussing / refining the other PR.

You have ignored my comment about the license header, your commits are not signed, the title of the PR is not indicative of what it does and the formatting recommendation (simply call 'mvn git-code-format:format-code -Dgcf.globPattern=**/*') seem  not to have been followed.

Would you mind having another try? Thanks!

**Comment by syefimov** [comment]
I will do it over weekend.
thank you.
________________________________

**Comment by syefimov** [comment]
I removed DeletionBolt.java, committed (signed)  formatted SolrSpout.java. I should create a separate branch for this commit in my repository. Will do it in a right way for a next one. 
Thank you.

**Comment by jnioche** [comment]
looks way better, thanks @syefimov 

I don't think the formatting has been applied. Could you please run 
`mvn git-code-format:format-code -Dgcf.globPattern=**/`
and push?

Would have been nice to be able to reproduce the problem that this PR is fixing but this would require #851 first

**Comment by jnioche** [comment]
Hi @syefimov, how can I help you make progress on this PR?

**Comment by syefimov** [comment]
Julien,
I was way to busy lately. I will try to finish it on weekends.

Sorry.
________________________________

**Comment by syefimov** [comment]
I put changes to the grouping query code,  run formatting script again and committed changes. Hope it will work this time.

**Comment by jnioche** [comment]
thanks a lot @syefimov, this is great

**Pull request merged**
